BEGIN;
DROP TABLE `app_calendar_repeat`;
DROP TABLE `app_calendar_calendarbookpremission`;
DROP TABLE `app_calendar_calendarbook`;
DROP TABLE `app_calendar_calendartypeexclude`;
DROP TABLE `app_calendar_calendartypeinclude`;
DROP TABLE `app_calendar_reminder`;
ALTER TABLE `app_calendar_todo` DROP FOREIGN KEY `parentTodo_id_refs_id_6be55c95`;
DROP TABLE `app_calendar_todo`;
DROP TABLE `app_calendar_activity`;
DROP TABLE `app_calendar_calendartype`;
COMMIT;
