class MessageBase():
	userNotExist = 'userNotExist'
	userExist = 'userExist'
	userNotActive = 'userNotActive'
	passwordNotEqual = 'passwordNotEqual'
	passwordWrong = 'passwordWrong'
	tooShort = 'tooShort'
	tooLong = 'tooLong'
	success = 'success'
	fail = 'fail'
	notEmail = 'notEmail'
